---
- name: Add postgresql repo
  yum:
    name: http://yum.postgresql.org/9.5/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}/pgdg-redhat95-9.5-2.noarch.rpm
- name: Install postgresql
  yum:
    name: postgresql95-server
- name: set pg_primary from ansible local of present
  set_fact: pg_primary={{ ansible_local.pg_primary.target }}
  when: ansible_local.pg_primary is defined
- name: Determine primary DB if none set
  include: select_primary.yml
  with_items: "{{ groups['postgres']|sort|first }}"
  when: pg_primary == ""
- name: if on primary system set status to primary
  set_fact: pg_status="primary"
  when: pg_primary == "{{ inventory_hostname }}"
- name: Initialise primary DB
  include: primary.yml
  when: pg_status == "primary"
- name: Build backup DBs
  include: backup.yml
  when: pg_status == "backup"
...
