---
- hosts: local
  roles:
    - libvirt

- hosts: all:!local
  roles:
    - common

- hosts: ipa
  roles:
    - ipaserver

- hosts: pg_cluster
  roles:
    - pg_cluster

- hosts: pgpool
  roles:
    - pgpool

- hosts: jenkins_slave
  roles:
    - jenkins_slave
    - rpm_builder

# - hosts: all:!ipa
#   remote_user: root
#   roles:
#       - ipaclient
#

- hosts: owncloud
  roles:
    - owncloud

- hosts: nextcloud
  roles:
    - nextcloud
...
