---
- hosts: fedora
  gather_facts: false
  pre_tasks:
    - name: install python and deps for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python
    - name: Gather facts
      setup:


- hosts: local
  roles:
    - libvirt

- hosts: all:!local
  roles:
    - common

- hosts: gitlab
  roles:
    - gitlab

- hosts: ipa
  roles:
    - ipaserver

- hosts: pg_cluster
  roles:
    - pg_cluster

- hosts: pgpool
  roles:
    - pgpool

- hosts: jenkins
  roles:
    - jenkins

- hosts: jenkins_slave
  roles:
    - jenkins_slave
    - rpm_builder

# - hosts: all:!ipa
#   remote_user: root
#   roles:
#       - ipaclient
#

- hosts: owncloud
  roles:
    - owncloud

- hosts: nextcloud
  roles:
    - nextcloud
...
