---
- hosts: local
  roles:
    - libvirt

- hosts: all:!local
  roles:
    - common

- hosts: gitlab
  roles:
    - gitlab

- hosts: ipa
  roles:
    - ipaserver

- hosts: postgres
  roles:
    - postgresql

- hosts: pgpool
  roles:
    - pgpool

- hosts: jenkins
  roles:
    - jenkins

- hosts: jenkins_slave
  roles:
    - jenkins_slave
    - rpm_builder

# - hosts: all:!ipa
#   remote_user: root
#   roles:
#       - ipaclient
...
