---
- name: Install mariadb server
  package:
    name: mariadb-server
    state: present
- name: Start and enable mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes
...
