---
- name: gather virtual machine names
  command: /usr/bin/virsh domid {{ item }}
  register: vmstatus
  with_items: "{{ test_vms  }}"
  ignore_errors: true
  no_log: true
- name: create virtual machines
  command: /usr/bin/virt-clone -o c7-template --auto-clone -n {{ item.item }}
  when: item|failed
  with_items: "{{ vmstatus.results }}"
  no_log: true
...
