---
- name: Add postgresql repo
  yum:
    name: http://yum.postgresql.org/9.5/redhat/rhel-{{ ansible_distribution_major_version  }}-{{ ansible_architecture  }}/pgdg-redhat95-9.5-2.noarch.rpm
- name: Install pgpool
  yum:
    name: pgpool-II-95
...
