---
- name: Install ssh key
  authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub')  }}"
  ignore_errors: true
  tags:
    - sshkeys
- name: Install selinux python bindings
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - libsemanage-python
- name: Set selinux to enforcing
  selinux:
    policy: targeted
    state: permissive
- name: Install python bindings for firewalld
  package:
    name: python2-firewall
    state: present
  when: ansible_distribution != "CentOS"
- name: Set hostname to vmname
  hostname: name={{ inventory_hostname }}.local.test
...
