---
- name: Install ssh key
  authorized_key:
    user: root
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub')  }}"
  tags:
    - sshkeys
- name: Install selinux python bindings
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python 
    - libsemanage-python 
- name: Set selinux to enforcing
  selinux: 
    policy: targeted 
    state: enforcing
- name: Install python bindings for firewalld
  package: 
    name: python2-firewall
    state: latest
- name: Set hostname to vmname
  hostname: name={{ inventory_hostname }}.local.test
...
