test_vms:
 - c7-pg_cluster01
 - c7-pg_cluster02
 - c7-pg_cluster03
 - c7-pgpool01
 - c7-pgpool02
 - c7-jenkins01
 - c7-jenkins-slave01

host_groups:
    c7-pg_cluster01:
        - pg_cluster
    c7-pg_cluster02:
        - pg_cluster
    c7-pg_cluster03:
        - pg_cluster
    c7-pgpool01:
        - pgpool
    c7-pgpool02:
        - pgpool
    c7-jenkins01:
        - jenkins
    c7-jenkins-slave01:
        - jenkins_slave
